docs: OCPP1.6: fixes and formatting
EVerest/EVerest-archived pull request #103
Opened 2023-09-19 15:51 UTC by Dominik-K

2023-09-19 16:12 UTC, Dominik-K commented on docs/tutorials/how_to_ocpp/index.rst
> +In addition the module calls the event handlers of the `libocpp` so that it can track the state of the charging station and trigger OCPP messages accordingly (e.g. MeterValues.req , StatusNotificatio
Each sentence on extra line that (next) diffs in PR-views are smaller.

2023-09-21 14:26 UTC, krealyt requested changes
Just check for "Trailing whitespaces" and "Line too long"s.

2023-09-21 14:26 UTC, krealyt commented on docs/tutorials/how_to_ocpp/index.rst
> +supporting all feature profiles including Plug&Charge and the Security Extensions.
On both of these lines, I get a "Line too long" warning. In the first line, there is an additional "Trailing whitespace" warning.

Can you check those and also following sections that you changed?

(If you have other rules configured in your IDE, let's check together as this is another topic for configuring IDE for contribution.)

2023-10-11 09:54 UTC, krealyt commented on docs/tutorials/how_to_ocpp/index.rst
> +supporting all feature profiles including Plug&Charge and the Security Extensions.
After 1:1 talk, I checked the linting extension currently in use by our documentation docker container. It is _doc8_ which comes via the _reStructuredText_ extension.

This will all have to be documented in the contribution guidelines. I will set that up.
Until then, I suggest to keep the following process:

1. Make changes to docs on your own branch.
2. Create PR and add me as reviewer.
3. After content review, I'll fix eventual line break warnings.
4. I'll merge.

Will also fix it in this PR here. So: Done! :)

2023-10-11 13:29 UTC, krealyt approved these changes

2023-10-11 13:30 UTC, merged