ci: add broken-link-checker
EVerest/EVerest-archived pull request #128
Opened 2024-01-05 09:42 UTC by DerMolly

2024-01-06 14:05 UTC, andistorm commented on .github/workflows/build-docs.yml
> +
```suggestion
      pdf_artefact_name:
        description: "Name of the pdf artefact"
        value: ${{ jobs.build-pdf.outputs.pdf_artefact_name }}}
    secretes:
```
The secrets field is missing here. Thats why the workflow fails currently
See https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow

2024-01-06 14:05 UTC, andistorm commented on .github/workflows/build-docs.yml
> +        value: ${{ jobs.build-html.outputs.html_artefact_name }}
```suggestion
        value: ${{ jobs.build-doc.outputs.html_artefact_name }}
```

2024-01-06 14:05 UTC, andistorm commented on .github/workflows/build-docs.yml
> +        value: ${{ jobs.build-pdf.outputs.pdf_artefact_name }}}
```suggestion
        value: ${{ jobs.build-doc.outputs.pdf_artefact_name }}}
```

2024-01-06 14:05 UTC, andistorm commented on .github/workflows/deploy-everest-doc.yml
> +      github_pages_repo: ${{ inputs.github_pages_repo }}
I would make similiar split as for check_for_broken_links.

Probably removing the trigger mechanism in [nightly workflow](https://github.com/EVerest/EVerest/blob/main/.github/workflows/nightly-everest-doc-build.yaml) and calling there `build-docs.yml` and `deploy-everest-doc.yml` similiar to `on_pull_request.yml`

2024-01-06 14:05 UTC, andistorm commented on .github/workflows/on_pull_request.yml
> +      html_artefact_name: ${{ needs.build-docs.outputs.html_artefact_name }}
```suggestion
      html_artefact_name: ${{ needs.build-docs.outputs.html_artefact_name }}

```

2024-01-06 14:05 UTC, andistorm commented on .github/workflows/check_for_broken_links.yml
`check_for_broken_links.yml` -> `check-for-broken-links`

2024-01-06 14:05 UTC, andistorm commented on .github/workflows/on_pull_request.yml
`on_pull_request.yml` -> `on-pull-request.yml`

2024-01-08 07:29 UTC, DerMolly commented on .github/workflows/build-docs.yml
> +
Done

2024-01-08 07:29 UTC, DerMolly commented on .github/workflows/build-docs.yml
> +        value: ${{ jobs.build-html.outputs.html_artefact_name }}
Done

2024-01-08 07:29 UTC, DerMolly commented on .github/workflows/build-docs.yml
> +        value: ${{ jobs.build-pdf.outputs.pdf_artefact_name }}}
Done

2024-01-08 07:40 UTC, DerMolly commented on .github/workflows/deploy-everest-doc.yml
> +      github_pages_repo: ${{ inputs.github_pages_repo }}
done

2024-01-08 07:43 UTC, DerMolly commented on .github/workflows/on_pull_request.yml
> +      html_artefact_name: ${{ needs.build-docs.outputs.html_artefact_name }}
done

2024-01-08 07:43 UTC, DerMolly commented on .github/workflows/check_for_broken_links.yml
done

2024-01-08 07:43 UTC, DerMolly commented on .github/workflows/on_pull_request.yml
done

2024-01-08 10:03 UTC, andistorm requested changes

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/on-pull-request.yml
Could you "register" this workflow by adding temporary the `push` event and test the workflow, please?

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/build-docs.yml
> +
you need to name here the required secrets in this case `SA_GITHUB_SSH_KEY` 

```suggestion
    secretes:
      SA_GITHUB_SSH_KEY:
        required: true
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/check-for-broken-links.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-22.04
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/build-docs.yml
> +        required: false
```suggestion
        required: true
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/build-docs.yml
> +        required: false
```suggestion
        required: true
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/build-docs.yml
> +        required: false
```suggestion
        required: true
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/build-docs.yml
> +        required: false
```suggestion
        required: true
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/build-docs.yml
> +        value: ${{ jobs.build-doc.outputs.html_artefact_name }}
```suggestion
        value: ${{ jobs.build-docs.outputs.html_artefact_name }}
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/build-docs.yml
> +        value: ${{ jobs.build-doc.outputs.pdf_artefact_name }}}
```suggestion
        value: ${{ jobs.build-docs.outputs.pdf_artefact_name }}}
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/build-docs.yml
> +  build-doc:
```suggestion
  build-docs:
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/check-for-broken-links.yml
> +        type: string
```suggestion
      html_artefact_name:
        description: 'html artifact name'
        required: true
        type: string
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/deploy-everest-doc.yml
>          description: 'Build PDF documentation?'
```suggestion
      build_pdf:
        description: 'Build PDF documentation?'
        required: true
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/deploy-everest-doc.yml
>          description: 'Build HTML documentation?'
```suggestion
      build_html:
        description: 'Build HTML documentation?'
        required: true
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/deploy-everest-doc.yml
>        deploy_html:
remove `default` field

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/deploy-everest-doc.yml
>          description: 'Snapshot file location: <owner>/<repo>/<ref>:<path-to-snapshot.yaml>'
```suggestion
      snapshot_file:
        description: 'Snapshot file location: <owner>/<repo>/<ref>:<path-to-snapshot.yaml>'
        required: true
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/deploy-everest-doc.yml
>          description: 'GithubPages repo: <owner>/<repo>'
```suggestion
      github_pages_repo:
        description: 'GithubPages repo: <owner>/<repo>'
        required: true
```

2024-01-08 10:03 UTC, andistorm commented on .github/workflows/deploy-everest-doc.yml
>          description: 'Overwrite existing documentation?'
remove `default` field

2024-01-08 18:48 UTC, DerMolly commented on .github/workflows/build-docs.yml
> +
done

2024-01-08 18:48 UTC, DerMolly commented on .github/workflows/check-for-broken-links.yml
> +    runs-on: ubuntu-latest
done

2024-01-08 18:50 UTC, DerMolly commented on .github/workflows/build-docs.yml
> +        required: false
done

2024-01-08 18:50 UTC, DerMolly commented on .github/workflows/build-docs.yml
> +        required: false
done

2024-01-08 18:50 UTC, DerMolly commented on .github/workflows/build-docs.yml
> +        required: false
done

2024-01-08 18:50 UTC, DerMolly commented on .github/workflows/build-docs.yml
> +        required: false
done

2024-01-08 18:51 UTC, DerMolly commented on .github/workflows/build-docs.yml
> +  build-doc:
done

2024-01-08 18:51 UTC, DerMolly commented on .github/workflows/build-docs.yml
> +        value: ${{ jobs.build-doc.outputs.pdf_artefact_name }}}
done

2024-01-08 18:51 UTC, DerMolly commented on .github/workflows/build-docs.yml
> +        value: ${{ jobs.build-doc.outputs.html_artefact_name }}
done

2024-01-08 18:52 UTC, DerMolly commented on .github/workflows/check-for-broken-links.yml
> +        type: string
done

2024-01-08 18:52 UTC, DerMolly commented on .github/workflows/deploy-everest-doc.yml
>          description: 'Build PDF documentation?'
done

2024-01-08 18:53 UTC, DerMolly commented on .github/workflows/deploy-everest-doc.yml
>          description: 'Build HTML documentation?'
done

2024-01-08 18:53 UTC, DerMolly commented on .github/workflows/deploy-everest-doc.yml
>        deploy_html:
done

2024-01-08 18:54 UTC, DerMolly commented on .github/workflows/deploy-everest-doc.yml
>          description: 'Snapshot file location: <owner>/<repo>/<ref>:<path-to-snapshot.yaml>'
done

2024-01-08 18:54 UTC, DerMolly commented on .github/workflows/deploy-everest-doc.yml
>          description: 'GithubPages repo: <owner>/<repo>'
done

2024-01-08 18:55 UTC, DerMolly commented on .github/workflows/deploy-everest-doc.yml
>          description: 'Overwrite existing documentation?'
done

2025-11-25 16:13 UTC, closed without merging

2025-11-26 18:26 UTC, felix-ulonska commented
**⚠️ PR Affected by Security Incident**

This PR was affected by a security incident where a compromised account force-pushed to this branch and closed the PR.

**✅ Branch History Restored**

We've run an automation that restored the complete history of this branch to the time before the attack. All your commits are preserved. Nothing has been updated in the respective branch in case someone force-pushed after the attack but before our automation.

**🔄 Action Required**

GitHub won't allow reopening this PR after the close and force-push. Please:
 - Open a new PR from your branch to the target branch. You can use the following link to open a new PR: [Open PR](https://github.com/EVerest/EVerest/compare/main...ci/broken-link-checker)
 - Link back to this PR in the description to include previous discussions

We apologize for the inconvenience.