Tutorial: How to Plug & Charge
EVerest/EVerest-archived pull request #150
Opened 2024-03-21 11:47 UTC by krealyt

2024-03-21 11:52 UTC, krealyt commented on docs/tutorials/how_to_plug_and_charge/index.rst
> +   under `dist/etc/certs`.
After running through the "Quick Start Guide", the certs are in dist/etc/everest/certs.

Please check if I did some customization or we have to change the path here in this tutorial.

2024-03-21 11:57 UTC, krealyt commented on docs/tutorials/how_to_plug_and_charge/index.rst
> +```
Probably run-scripts dir in the build directory is meant. If true, set a dash instead of the underscore in the directory name.

2024-03-26 10:09 UTC, andistorm requested changes
@Pietfried , please validate the comments @krealyt made. In my "random" setup he is right

2024-03-26 10:09 UTC, andistorm commented on docs/tutorials/how_to_plug_and_charge/index.rst
> +./run_scripts/run-sil-ocpp201-pnc.sh
```suggestion
./run-scripts/run-sil-ocpp201-pnc.sh 
```

2024-03-26 10:09 UTC, andistorm commented on docs/tutorials/how_to_plug_and_charge/index.rst
> +./run_scripts/run-sil-ocpp-pnc.sh
```suggestion
./run-scripts/run-sil-ocpp-pnc.sh 
```

2024-03-26 10:09 UTC, andistorm commented on docs/tutorials/how_to_plug_and_charge/index.rst
> +   under `dist/etc/certs`.
```suggestion
   under `dist/everest/etc/certs`.
```

2024-03-26 15:39 UTC, andistorm approved these changes
LGTM partial: format and integration in existing doc

I didn't go through the tutorial

2024-03-26 15:51 UTC, merged