Revised README.md
EVerest/EVerest-archived pull request #188
Opened 2024-08-15 13:42 UTC by nserway

The team updated various sections of the README to ensure that the document was more concise, had the necessary embedded links, and added links for additional for access to the mailing list, zulip chat, and the community meetings. 

The team updated the README to align it with GitHub Best Practices and mimic successful large scale repositories that are widely know for their impeccable documentation.

2024-08-30 15:36 UTC, nserway commented
@krealyt Hi Manuel, the JOET team is taking a pass at updating the documentation for various repositories README's. We did some research alongside our development team and modified the EVerest - EVerest repository README to align with GitHub best practices, include more relevant information, and improve readability. Shankari is reviewing this PR but, if you wanted to take a look at it in parallel that would be very helpful. Thanks!

2024-09-03 07:28 UTC, krealyt requested changes
I left some comments, mostly about Codacy analysis. Thanks for your contribution.

2024-09-03 07:28 UTC, krealyt commented on README.md
> -[![OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/projects/6739/badge)](https://bestpractices.coreinfrastructure.org/projects/6739)
Did you remove the badge intentionally or has this been removed unintentionally?

2024-09-03 07:28 UTC, krealyt commented on README.md
> -[![OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/projects/6739/badge)](https://bestpractices.coreinfrastructure.org/projects/6739)
Please also check the Codacy Analysis result. I get a "First line in a file should be a top-level heading."

That should have been a problem already before your changes. Probably Codacy was not active when updating the first lines for the last time?

2024-09-03 07:28 UTC, krealyt commented on README.md
> +### Full Stack Hardware Requirements:
Please check headline level. Should be h2 rather than h3, as I understand.

2024-09-03 07:28 UTC, krealyt commented on README.md
> +Additionally, if you or your organization would like to set up a 30 minute 1:1 meeting with EVerest leadership. Please follow the link [here.](https://calendly.com/manuel-ziegler-pionix/30min?month=2
I would not call it "leadership", because it would give that 1:1 talk a too strong sense of business level - which it is definitely not.

It is more a non-technical community talkto lead people the way into the communication channels and working groups if they feel lost in the beginning.

2024-09-03 07:28 UTC, krealyt commented on README.md
> -[![OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/projects/6739/badge)](https://bestpractices.coreinfrastructure.org/projects/6739)
See my additional inline comments in the review and also the Codacy analysis results.

Rest looks good. So, if you have changed the open stuff, we can publish your improvements. :)

2024-09-03 07:28 UTC, krealyt commented on README.md
> +EVerest is a Linux Foundation backed open-source modular framework for settong up a full stack environment for EV charging. The modular software architecture fosters customizablility and lets you con
Small typo: -> sett[i]ng up

2024-09-03 17:37 UTC, nserway commented on README.md
> +Additionally, if you or your organization would like to set up a 30 minute 1:1 meeting with EVerest leadership. Please follow the link [here.](https://calendly.com/manuel-ziegler-pionix/30min?month=2
resolved by removing "EVerest Leadership" alltogether

2024-09-03 17:41 UTC, nserway commented on README.md
> -[![OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/projects/6739/badge)](https://bestpractices.coreinfrastructure.org/projects/6739)
Badge was removed unintentionally, added it back in!

As far as the Codacy analysis: I am not sure I agree with "First Line in a file should be a top-level heading" as we have the EVerest logo as the introduction on our opening page.

2024-09-04 22:57 UTC, shankari approved these changes
I have several comments, but they can all be deferred to a cleanup change.
This is strictly better than what we have now, and I am a big fan of making things better incrementally.

@nserway please do create a separate PR to fix the issues listed here.

2024-09-04 22:57 UTC, shankari commented on README.md
> +# Main Features
the list of main features will change over time. Who is going to maintain this list?

2024-09-04 22:57 UTC, shankari commented on README.md
> +It is recommended to have at least 4GB of RAM available to build EVerest. More CPU cores will optionally boost the build process, while requiring more RAM accordingly.
this is interesting, but most people are going to care about the resources required to _run_ EVerest. You can build EVerest in the cloud or on your full-power laptop. The most frequently asked question among the early adopters was focused on the runtime resources required.

2024-09-04 22:57 UTC, shankari commented on README.md
> +Additionally, if you and/or your organization would like to set up a 30 minute 1:1 meeting please follow the link [here.](https://calendly.com/manuel-ziegler-pionix/30min?month=2024-08)
```suggestion
Additionally, if you and/or your organization would like to set up a 30 minute 1:1 meeting with a member of the EVerest community, please follow the link [here.](https://calendly.com/manuel-ziegler-pionix/30min?month=2024-08)
```

Will other community members ever volunteer for this? If so, we may want to make this a generic link that is potentially backed by multiple members, instead of being linked to Manuel.

2024-09-05 18:29 UTC, nserway commented
I will create a new PR that addresses the comments you brought up @shankari 

Thanks!

2024-09-10 14:15 UTC, nserway commented on README.md
> +It is recommended to have at least 4GB of RAM available to build EVerest. More CPU cores will optionally boost the build process, while requiring more RAM accordingly.
@shankari  - Agreed! Just wanted to clarify - are we talking about the other libraries are needed to run EVerest (i.e., the documentation that is in EDM [[here](https://everest.github.io/nightly/dev_tools/edm.html)])

2024-09-10 22:43 UTC, shankari commented on README.md
> +It is recommended to have at least 4GB of RAM available to build EVerest. More CPU cores will optionally boost the build process, while requiring more RAM accordingly.
No, i am talking about the CPU/memory/disk space required to run EVerest

2024-09-12 08:54 UTC, krealyt commented on README.md
> +It is recommended to have at least 4GB of RAM available to build EVerest. More CPU cores will optionally boost the build process, while requiring more RAM accordingly.
@shankari Please have a look at this PR here: https://github.com/EVerest/EVerest/pull/191/files

It has been merged just today, so the changes will be on everest.github.io after the next nightly build. Eventually this suits the requirement you described here.

2024-09-12 08:55 UTC, krealyt commented on README.md
> -[![OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/projects/6739/badge)](https://bestpractices.coreinfrastructure.org/projects/6739)
@nserway I will look into that and clarify, how to configure Codacy so that it suits our needs. I agree with you that this rule is not what we would want in all cases.

2024-09-13 16:10 UTC, nserway commented
@krealyt Revised the README to fix the Codacy analysis changes. There are 2 remaining changes that did not pass the check. The first is the top level heading that we discussed earlier. The second is the Line 6 heading change which I also do not agree with. Please let me know how to proceed.

2024-09-16 12:46 UTC, krealyt commented on README.md
> +# Main Features
Created a separate issue for this: https://github.com/EVerest/EVerest/issues/195

2024-09-16 12:53 UTC, krealyt commented on README.md
> +Additionally, if you and/or your organization would like to set up a 30 minute 1:1 meeting please follow the link [here.](https://calendly.com/manuel-ziegler-pionix/30min?month=2024-08)
Unsure about that. I really do not insist on being the only one providing this talk. :)

But I think, people supporting me in this should know the community tools and also have a good overview of the project's daily doings. No deep tech knowledge is required but some EVerest software architectural understanding would be great, I think.

Shall we perhaps add to the contribution file that also non-development-related support is appreciated and name that 1:1 talks as one example? What do you think?

2024-09-16 12:55 UTC, krealyt commented
> @krealyt Revised the README to fix the Codacy analysis changes. There are 2 remaining changes [...]

Will clarify this topic. We need that Codacy config changes probably also in other repositories.

2024-09-16 12:56 UTC, krealyt commented
Looks to me that we can merge this one as soon as we have clarified / changed the Codacy issue (see discussion above).

2024-09-16 14:00 UTC, krealyt approved these changes

2024-09-16 14:13 UTC, krealyt commented on README.md
> -[![OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/projects/6739/badge)](https://bestpractices.coreinfrastructure.org/projects/6739)
For the records: The Codacy rules are not mandatory (anymore?) for this repository. If we decide during review that some Codacy results are not what we want in a specific case, let's move on and merge. And this is, what we should do here. :)

FYI @nserway @shankari

2024-09-16 14:18 UTC, merged