Fixed links after docu modularization
EVerest/EVerest-archived pull request #61
Opened 2023-03-10 15:14 UTC by krealyt

2023-03-27 14:05 UTC, andistorm requested changes
Looks good in gernal.
Maybe we should consider to rework all links and switch to Explicit or Implicit targets:
https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html

2023-03-27 14:05 UTC, andistorm commented on docs/dev_tools/edm.rst
> +Make sure you have installed `ev_cli <ev-cli.html>`_ first.
```suggestion
Make sure you have installed `ev_cli <ev_cli.html>`_ first.
```

2023-03-27 14:05 UTC, andistorm commented on docs/dev_tools/edm.rst
> +Make sure you have installed `ev_cli <ev-cli.html>`_ first.
Wrong Link here

2023-03-31 08:51 UTC, krealyt commented on docs/dev_tools/edm.rst
> +Make sure you have installed `ev_cli <ev-cli.html>`_ first.
@andistorm OK, understood. Suggestion as I cannot do that currently: Let's fix the links in this PR now and do the "proper" repair as suggested by you in a second step. OK?

2023-04-03 15:49 UTC, andistorm commented on docs/dev_tools/edm.rst
> +Make sure you have installed `ev_cli <ev-cli.html>`_ first.
@krealyt, yes I made a commit to fix at least this single link (dash to underscore), If it ok for you, you can merge

2023-04-03 15:50 UTC, andistorm approved these changes

2023-04-03 15:53 UTC, merged