Updated SIL docu in quick start and tutorial
EVerest/EVerest-archived pull request #69
Opened 2023-06-12 08:36 UTC by krealyt

The following topics should be checked by a second pair of eyes:
- Docker container startup has been changed in documentation. No more StEVe and MariaDB startup for SIL now anymore. Will users get errors somewhere else in the doc now due to StEVe not running?
- The process for setting up custom SIL flows is new on the tutorial page. It contains downloading a changed json file and restarting the mqtt-server via Docker container. I tested that, but I am not sure if there is no easier way to do this.

Most important changes in general:
- Quick start guide only contains the first setup of the simulation without customization.
- Customization doc started on tutorial chapter - will have to be enhanced in future with a dedicated example.
- New Docker setup process has been described.

2023-06-19 14:26 UTC, Pietfried requested changes

2023-06-19 14:26 UTC, Pietfried commented on docs/general/02_quick_start_guide.rst
>  Prepare The Helpers
I would summarize the available docker containers here and explain them a little bit:
* Mosquitto (MQTT Broker, always required to run EVerest)
* SteVe (only required if OCPP is configured)
* NodeRED (GUI to monitor EVerest and control/run simulations)

To me its important to highlight that actually only Mosquitto is required to run EVerest, everything else is tooling around simulation / ocpp

2023-06-19 14:26 UTC, Pietfried commented on docs/general/02_quick_start_guide.rst
> +To get all this working, make sure you have Docker and Docker-Compose installed during the previous install phase. (If not, see install instructions for `Docker <https://docs.docker.com/engine/instal
docker and docker-compose

2023-06-19 14:26 UTC, Pietfried commented on docs/general/02_quick_start_guide.rst
> +  sudo docker-compose up -d mqtt-server
Explain what this line actually does by adding something like:

"This will start up a mosquitto broker which will be used by EVerest for 
the communication between the EVerest modules."

2023-06-19 14:26 UTC, Pietfried commented on docs/general/02_quick_start_guide.rst
> +After having done that, change to the directory /everest-core/build/, which has
everest-core/build
instead of
/everest-core/build

2023-06-19 14:26 UTC, Pietfried commented on docs/general/02_quick_start_guide.rst
>  We will startup EVerest now with a software-in-a-loop (SIL) config.
Add something like: 

> This will start EVerest as a simple AC charging station with software-in-the-loop configuration. This means that all hardware related parts like Powermeter, RFID-Reader or even actual Electric Vehicles are loaded as simulated modules.

2023-06-19 14:26 UTC, Pietfried commented on docs/general/02_quick_start_guide.rst
>  Start the software-in-a-loop simulation via script:
I think

> Start EVerest with a software-in-the-loop configuration 

makes it more clear that it is actually EVerest whats been started using this command.

2023-06-19 14:26 UTC, Pietfried commented on docs/tutorials/run_sil/index.rst
> +Your modified flow will now be used for your Simulation GUI at `http://localhost/1880/gui`.
http://localhost:1880/ui

2023-06-19 14:26 UTC, Pietfried commented on docs/general/02_quick_start_guide.rst
> +  cd {EVerest Workspace Directory}/everest-utils/docker
befote you also used ~/checkout instead of {EVerest Workspace directory}

2023-06-19 14:26 UTC, Pietfried commented on docs/general/02_quick_start_guide.rst
> +EVerest comes with prepared Docker containers. One of them is needed to get the
I would generally prefer "required" over "needed" in those contexts

2023-06-19 17:42 UTC, krealyt commented on docs/general/02_quick_start_guide.rst
>  Prepare The Helpers
Added a clarification and linked to the Docker tutorial page. That will have to be updated in another PR which I will create separately.

2023-06-19 17:59 UTC, krealyt commented on docs/general/02_quick_start_guide.rst
> +To get all this working, make sure you have Docker and Docker-Compose installed during the previous install phase. (If not, see install instructions for `Docker <https://docs.docker.com/engine/instal
Changed in current commit.

2023-06-19 17:59 UTC, krealyt commented on docs/general/02_quick_start_guide.rst
> +  sudo docker-compose up -d mqtt-server
Used your suggestion.

2023-06-19 17:59 UTC, krealyt commented on docs/general/02_quick_start_guide.rst
> +After having done that, change to the directory /everest-core/build/, which has
Changed, thanks!

2023-06-19 18:00 UTC, krealyt commented on docs/general/02_quick_start_guide.rst
>  We will startup EVerest now with a software-in-a-loop (SIL) config.
Used as suggested.

2023-06-19 18:00 UTC, krealyt commented on docs/general/02_quick_start_guide.rst
>  Start the software-in-a-loop simulation via script:
Changed some sentences to make it clearer in general.

2023-06-19 18:00 UTC, krealyt commented on docs/tutorials/run_sil/index.rst
> +Your modified flow will now be used for your Simulation GUI at `http://localhost/1880/gui`.
Nice one. :)

2023-06-19 18:02 UTC, krealyt commented on docs/general/02_quick_start_guide.rst
> +  cd {EVerest Workspace Directory}/everest-utils/docker
Defined the variable for the checkout directory in the beginning of the quick start guide now and changed all occurrences to the variable now. Thanks.

2023-06-19 18:02 UTC, krealyt commented on docs/general/02_quick_start_guide.rst
> +EVerest comes with prepared Docker containers. One of them is needed to get the
Got it, thx. Changed one other occurrence in the quick start guide. :)

2023-06-20 06:58 UTC, krealyt commented on docs/tutorials/run_sil/index.rst
> +Your modified flow will now be used for your Simulation GUI at `http://localhost/1880/gui`.
Fixed another URL on that page a minute ago.

2023-07-07 07:20 UTC, Pietfried approved these changes

2023-07-07 13:26 UTC, merged